from argparse import Namespace
from pathlib import Path

import pytest

from miles.utils.audit_utils.config_snapshot.generated_values import GENERATED_VALUES_ENV_VAR, read_generated_values
from miles.utils.audit_utils.config_snapshot.storage import ConfigSnapshotStorage
from miles.utils.external_utils.command_utils.helm_backend.launcher.entrypoint import _resolve_wandb_run_id
from miles.utils.test_utils.snapshot import SNAPSHOT_RECORD_DIR_ENV_VAR
from miles.utils.tracking_utils.wandb_utils import init_wandb_primary


class TestTrackingProvenance:
    @pytest.mark.parametrize("preassigned", [False, True])
    def test_primary_records_only_automatically_generated_ids(
        self, wandb_capture_args: Namespace, tmp_path: Path, preassigned: bool
    ) -> None:
        """A fresh SDK ID is recorded as generated while an explicitly resumed ID stays literal."""
        if preassigned:
            wandb_capture_args.wandb_run_id = "automatic-id"
        init_wandb_primary(wandb_capture_args)
        records = ConfigSnapshotStorage(directory=tmp_path).read()
        tracking = [record for record in records if record.point.stage == "tracking_config"]
        assert len(tracking) == (0 if preassigned else 1)
        if tracking:
            assert [(entry.kind, entry.value) for entry in tracking[0].generated_values] == [("wandb_run_id", "automatic-id")]
            assert tracking[0].context == next(record for record in records if record.point.stage == "process_config").context

    @pytest.mark.parametrize("source", ["generated", "given", "installed"])
    def test_helm_reused_ids_need_existing_generation_provenance(
        self, monkeypatch: pytest.MonkeyPatch, source: str
    ) -> None:
        """Only an ID generated by this Helm launch acquires normalization provenance."""
        monkeypatch.setenv(SNAPSHOT_RECORD_DIR_ENV_VAR, "/snapshot/records")
        monkeypatch.delenv(GENERATED_VALUES_ENV_VAR, raising=False)
        monkeypatch.setattr("wandb.sdk.lib.runid.generate_id", lambda: "automatic-id")
        args = Namespace(use_wandb=True, wandb_run_id="automatic-id" if source == "given" else None)
        payload = {"args": {"wandb_run_id": "automatic-id"}} if source == "installed" else None
        assert _resolve_wandb_run_id(args, installed_payload=payload) == "automatic-id"
        assert bool(read_generated_values()) is (source == "generated")
